# Generated by Django 3.2.5 on 2021-07-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order_id', models.PositiveBigIntegerField()),
                ('order_status', models.BooleanField()),
                ('user_id', models.PositiveIntegerField()),
                ('restaurant_id', models.PositiveIntegerField()),
                ('device_token', models.CharField(max_length=200)),
                ('user_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('user_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('restaurant_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('restaurant_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('food_id', models.PositiveIntegerField()),
                ('user_notes', models.TextField()),
                ('driver_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
