# Generated by Django 3.2.5 on 2021-08-04 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_order_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.BooleanField(default=False)),
                ('loyalty', models.BooleanField(default=False)),
                ('food_ordering', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_statuses', to='core.order')),
            ],
        ),
    ]
